# In your static/admin/config.yml file

backend: 
    name: github
    repo: haydn5/netlify-cms-test-2

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro text, name: intro, widget: text}
          - {label: Image, name: image, required: false, widget: image}